// Official BBQ Korea menu names/photos. Prices are game economy settings.
export const BBQ_MENU = {
  golden: {
    name: '황금올리브치킨',
    price: 23000,
    sell: 9000,
    hp: 60,
    energy: 0,
    food: 1,
    image: '/bbq/golden.jpg',
    description: '바삭한 튀김옷과 촉촉한 속살',
  },
  halfchicken: {
    name: '황올 반+양념 반',
    price: 24000,
    sell: 9500,
    hp: 65,
    energy: 0,
    food: 1,
    image: '/bbq/half.png',
    description: '후라이드와 달콤한 양념을 반씩',
  },
  hotchicken: {
    name: '황금올리브치킨 핫크리스피',
    price: 24000,
    sell: 9500,
    hp: 65,
    energy: 0,
    food: 1,
    image: '/bbq/hot.jpg',
    description: '하바네로와 향신료의 매콤한 맛',
  },
  cheesechicken: {
    name: '뿜치킹',
    price: 25000,
    sell: 10000,
    hp: 70,
    energy: 0,
    food: 1,
    image: '/bbq/cheese.jpg',
    description: '네 가지 치즈의 풍미',
  },
  jamaica: {
    name: '자메이카 통다리구이',
    price: 24000,
    sell: 9500,
    hp: 65,
    energy: 0,
    food: 1,
    image: '/bbq/jamaica.jpg',
    description: '저크 소스를 발라 구운 통다리',
  },
  saucechicken: {
    name: '황금올리브치킨 양념',
    price: 24500,
    sell: 9500,
    hp: 65,
    energy: 0,
    food: 1,
    image: '/bbq/sauce.jpg',
    description: '사과와 당근을 더한 부드러운 단맛',
  },
} as const;
export type BbqItem = keyof typeof BBQ_MENU;
