import * as T from 'three';
import {body,collide,integrate,type Body} from './physics';
import {person,damagePerson,combatStep,hitPerson,vehiclePerson,stepPerson,type Person} from './pedestrians';
type Hud={hp:number;hurt:boolean;speed:number;driving:boolean;mission:number;distance:number;paused:boolean;hint:string;error:string};
export type GameApi={dispose:()=>void;pause:()=>void;reset:()=>void;attack:()=>void;key:(k:string,v:boolean)=>void;interact:()=>void};
export function createGame(host:HTMLDivElement,report:(h:Hud)=>void):GameApi{
const scene=new T.Scene();scene.background=new T.Color('#b6c7cb');scene.fog=new T.Fog('#b6c7cb',90,260);const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;host.appendChild(renderer.domElement);const camera=new T.PerspectiveCamera(53,1,.1,350);scene.add(new T.HemisphereLight('#d6ebff','#b39b7c',2.3));const sun=new T.DirectionalLight('#ffe4b5',3.2);sun.position.set(-55,85,35);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-110,right:110,top:110,bottom:-110,far:250});sun.shadow.bias=-.001;scene.add(sun);
const solids:{x:number;z:number;w:number;d:number}[]=[];const mats=new Map<string,T.MeshStandardMaterial>();function mat(c:string){if(!mats.has(c))mats.set(c,new T.MeshStandardMaterial({color:c,roughness:.85}));return mats.get(c)!}function box(w:number,h:number,d:number,c:string,x:number,y:number,z:number,parent:T.Object3D=scene){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function sign(txt:string,w:number,x:number,y:number,z:number,bg='#203a38'){const c=document.createElement('canvas');c.width=768;c.height=160;const ctx=c.getContext('2d')!;ctx.fillStyle=bg;ctx.fillRect(0,0,768,160);ctx.fillStyle='#f6ebd5';ctx.font='bold 70px Arial, Malgun Gothic';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(txt,384,83,730);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;const m=new T.Mesh(new T.PlaneGeometry(w,2),new T.MeshStandardMaterial({map:tex}));m.position.set(x,y,z);scene.add(m)}
box(240,.2,240,'#71836a',0,-.2,0);for(const z of [-65,0,65])box(235,.12,z===0?20:15,'#555e60',0,0,z);for(const x of [-70,0,70])box(x===0?18:15,.13,220,'#555e60',x,0,0);for(let a=-110;a<=110;a+=8){box(3,.02,.17,'#e0c88a',a,.1,0);box(.17,.02,3,'#e0c88a',0,.1,a)}for(const z of [-65,0,65])for(const x of [-70,0,70])for(let i=-4;i<=4;i++){box(1,.025,5,'#e7e4d6',x+i*1.6,.11,z+12);box(5,.025,.9,'#e7e4d6',x+12,.11,z+i*1.5)}
const names=['성수 로스터리','SEONGSU GARAGE','벽돌상회','오후의 커피','성수 작업실','STUDIO 02','수제화 공방','연무장 카페','SEOUL SUPPLY','성수 문구'];let n=0;for(const x of [-100,-40,40,100])for(const z of [-96,-36,36,96]){const w=30,d=34,h=8+n%4*3;box(w+5,.3,d+5,'#b6b4a5',x,.12,z);box(w,h,d,['#925f4a','#a36b50','#777773','#a47b60'][n%4],x,h/2,z);solids.push({x,z,w:w+1,d:d+1});box(w+1,.55,d+1,'#615f57',x,h+.1,z);box(9,2,8,'#89877c',x+3,h+1,z);for(let yy=5;yy<h;yy+=4)for(let xx=-11;xx<14;xx+=5){box(3,2.2,.14,'#344b50',x+xx,yy,z+d/2+.1);box(.08,2.2,.18,'#a1aaa1',x+xx,yy,z+d/2+.2)}for(let yy=1;yy<h;yy+=.7)box(w,.035,.04,'#bd9272',x,yy,z+d/2+.05);box(w-4,3.3,.16,'#253e40',x,1.8,z+d/2+.2);for(let j=-12;j<14;j+=4)box(.15,3.4,.23,'#aa9981',x+j,1.8,z+d/2+.3);sign(names[n%names.length],w-3,x,5.8,z+d/2+.3);box(w-2,.25,2.8,n%2?'#dad1b8':'#345b4b',x,4.3,z+d/2+1);n++}
function tree(x:number,z:number){box(.5,4,.5,'#625843',x,2,z);const m=new T.Mesh(new T.IcosahedronGeometry(2.5,1),mat('#52775a'));m.scale.y=1.25;m.position.set(x,5,z);m.castShadow=true;scene.add(m)}for(let i=-105;i<=105;i+=15){if(Math.abs(i)>12){tree(i,15);tree(i,-15)}if(Math.abs(i)>20)tree(13,i)}for(let i=0;i<18;i++){const x=-110+(i*37)%220,z=i%2?119:-119;box(13,25+i%5*8,12,'#93a2a0',x,12+i%5*4,z)}for(let i=-100;i<=100;i+=30){box(.17,7,.17,'#384443',i,3.5,11);box(2,.18,.5,'#d3ccab',i+.7,7,11);box(2,1,.6,'#7b5e46',i,.6,17)}box(2,24,2,'#927664',-98,12,-42);box(2,20,2,'#927664',-93,10,-42);sign('성수역  ②',12,3,7,-13,'#245e45');box(.3,7,.3,'#697368',-3,3.5,-13);box(.3,7,.3,'#697368',9,3.5,-13);
function car(color:string,x:number,z:number){const g=new T.Group();box(2.3,.65,4.3,color,0,.85,0,g);box(2,.8,2.1,color,0,1.5,-.15,g);box(1.84,.62,.08,'#27444a',0,1.54,.95,g);box(1.84,.62,.08,'#27444a',0,1.54,-1.23,g);for(const s of [-1,1]){box(.06,.56,1.8,'#27444a',s*1.02,1.55,-.13,g);for(const zz of [-1.35,1.35]){const m=new T.Mesh(new T.CylinderGeometry(.47,.47,.25,12),mat('#20292b'));m.rotation.z=Math.PI/2;m.position.set(s*1.15,.53,zz);g.add(m)}box(.6,.22,.05,'#ffedb5',s*.7,.9,2.17,g);box(.55,.18,.05,'#ae3f2c',s*.7,.95,-2.17,g)}g.position.set(x,0,z);scene.add(g);return g}const ride=car('#df7740',5,8);
 type Vehicle={mesh:T.Group;physics:Body;route:T.Vector3[];waypoint:number;cruise:number;spawn:Body};
 const vehicles:Vehicle[]=[];
 function vehicle(mesh:T.Group,angle:number,route:T.Vector3[]=[],waypoint=0,cruise=9){const p=body(mesh.position.x,mesh.position.z,angle);const v={mesh,physics:p,route,waypoint,cruise,spawn:{...p}};mesh.rotation.y=angle;vehicles.push(v);return v}
 const controlled=vehicle(ride,0);
 const loop=[new T.Vector3(-65,0,5),new T.Vector3(65,0,5),new T.Vector3(65,0,60),new T.Vector3(-65,0,60)];
 for(let i=0;i<8;i++){const route=i<4?loop:loop.map(p=>new T.Vector3(p.x,0,-p.z)).reverse();const index=i%4,next=(index+1)%4,start=route[index].clone().lerp(route[next],.25);const heading=Math.atan2(route[next].x-start.x,route[next].z-start.z);vehicle(car(['#d8d9cd','#426d70','#beb99d','#8c5959'][i%4],start.x,start.z),heading,route,next,7+i%3)}
 let hp=100,hurtTimer=0;let attackTime=0,attackCooldown=0,notice='',noticeTime=0,shake=0,accumulator=0;
 const sparks:T.Mesh[]=[];for(let i=0;i<12;i++){const spark=new T.Mesh(new T.BoxGeometry(.1,.1,.35),new T.MeshBasicMaterial({color:'#ffe495'}));spark.visible=false;scene.add(spark);sparks.push(spark)}let sparkLife=0;const sparkOrigin=new T.Vector3();
 function impactEffect(x:number,z:number,power:number){if(power<3)return;shake=Math.min(.6,power*.025);sparkLife=.35;sparkOrigin.set(x,1,z);notice='충돌! 차량이 충격 방향으로 밀려납니다';noticeTime=1.7}

const player=new T.Group();box(.7,.95,.4,'#eee8d5',0,1.25,0,player);box(.44,.43,.43,'#d0a17c',0,1.95,0,player);box(.46,.15,.45,'#272b2b',0,2.18,0,player);const legs=[box(.25,.8,.3,'#3d5264',-.2,.42,0,player),box(.25,.8,.3,'#3d5264',.2,.42,0,player)];box(.2,.8,.25,'#eee8d5',-.46,1.2,0,player);const fist=box(.2,.8,.25,'#eee8d5',.46,1.2,0,player);scene.add(player);player.position.set(5,0,13);
const people:{mesh:T.Group;state:Person;spawn:Person;bar:T.Group;fill:T.Mesh;arm:T.Mesh}[]=[];for(let i=0;i<12;i++){const g=new T.Group();box(.6,.85,.4,['#61787f','#c8b594','#914f40'][i%3],0,1.1,0,g);box(.4,.4,.4,'#c6a383',0,1.8,0,g);box(.4,.7,.3,'#354545',0,.4,0,g);g.position.set(-100+i*17,0,13);scene.add(g);const state=person(i,g.position.x,g.position.z);const bar=new T.Group();const bg=new T.Mesh(new T.PlaneGeometry(2,.24),new T.MeshBasicMaterial({color:'#182526',side:T.DoubleSide}));bar.add(bg);const fill=new T.Mesh(new T.PlaneGeometry(1.9,.15),new T.MeshBasicMaterial({color:'#86df88',side:T.DoubleSide}));fill.position.z=.01;bar.add(fill);scene.add(bar);const arm=box(.22,.7,.25,'#c6a383',.43,1.1,0,g);people.push({mesh:g,state,spawn:{...state},bar,fill,arm})}const targets=[new T.Vector3(40,0,-14),new T.Vector3(-70,0,48),new T.Vector3(3,0,-10)];const ring=new T.Mesh(new T.TorusGeometry(3,.13,8,40),new T.MeshBasicMaterial({color:'#eaff79'}));ring.rotation.x=-Math.PI/2;scene.add(ring);const beam=new T.Mesh(new T.CylinderGeometry(.8,.8,16,16,1,true),new T.MeshBasicMaterial({color:'#eaff79',transparent:true,opacity:.19,depthWrite:false,side:T.DoubleSide}));scene.add(beam);
let driving=false,speed=0,yaw=0,orbit=.5,mission=0,paused=false,frame=0,last=performance.now(),elapsed=0,lastHud=0,drag=false,px=0;const keys:Record<string,boolean>={};const blocked=(x:number,z:number,r:number)=>Math.abs(x)>113||Math.abs(z)>110||solids.some(b=>Math.abs(x-b.x)<b.w/2+r&&Math.abs(z-b.z)<b.d/2+r);
function attack(){if(hp<=0||paused||driving||attackCooldown>0)return;attackTime=.28;attackCooldown=.48;const dir=new T.Vector3(Math.sin(player.rotation.y),0,Math.cos(player.rotation.y));let hit=false;for(const v of vehicles){const delta=v.mesh.position.clone().sub(player.position);const distance=delta.length();if(distance<4.2&&delta.normalize().dot(dir)>.35){v.physics.vx+=dir.x*.8;v.physics.vz+=dir.z*.8;v.physics.spin+=.12;v.physics.stun=Math.max(v.physics.stun,.7);impactEffect(v.physics.x,v.physics.z,3);hit=true;break}}if(!hit){const candidates=people.map(p=>({p,delta:new T.Vector3(p.state.x-player.position.x,0,p.state.z-player.position.z)})).filter(({p,delta})=>p.state.hp>0&&delta.length()<2.7&&delta.clone().normalize().dot(dir)>.25).sort((a,b)=>a.delta.lengthSq()-b.delta.lengthSq());if(candidates.length){const target=candidates[0].p.state;hit=hitPerson(target,dir.x,dir.z,5.5);if(hit)damagePerson(target,25)}}notice=hit?'타격!':'주먹 공격';noticeTime=.6}
function interact(){if(hp<=0||paused)return;if(driving){if(Math.hypot(controlled.physics.vx,controlled.physics.vz)>3){notice='속도를 줄인 뒤 내리세요';noticeTime=1.5;return}for(const s of [1,-1]){const x=ride.position.x+Math.cos(yaw)*3*s,z=ride.position.z-Math.sin(yaw)*3*s;if(!blocked(x,z,.5)&&!vehicles.some(v=>v!==controlled&&Math.hypot(v.physics.x-x,v.physics.z-z)<3)){driving=false;speed=0;player.visible=true;player.position.set(x,0,z);break}}}else if(player.position.distanceTo(ride.position)<6){driving=true;player.visible=false;yaw=ride.rotation.y;speed=0;orbit=.3}}
function clear(){Object.keys(keys).forEach(k=>keys[k]=false);drag=false}
function reset(){hp=100;hurtTimer=0;driving=false;speed=0;mission=0;paused=false;orbit=.5;yaw=0;attackTime=attackCooldown=noticeTime=shake=accumulator=sparkLife=0;vehicles.forEach(v=>{Object.assign(v.physics,v.spawn);v.mesh.position.set(v.physics.x,0,v.physics.z);v.mesh.rotation.set(0,v.physics.angle,0);if(v.route.length)v.waypoint=(vehicles.indexOf(v)-1)%4+1,v.waypoint%=4});people.forEach(p=>{Object.assign(p.state,p.spawn);p.mesh.position.set(p.state.x,0,p.state.z);p.mesh.rotation.set(0,p.state.heading,0)});player.position.set(5,0,13);player.rotation.x=0;player.visible=true;clear()}
function physicsStep(dt:number,f:number,turn:number){for(const v of vehicles){const p=v.physics;const fx=Math.sin(p.angle),fz=Math.cos(p.angle);if(v===controlled&&driving){const forward=p.vx*fx+p.vz*fz;const thrust=f*(forward*f<0?27:17);p.vx+=fx*thrust*dt;p.vz+=fz*thrust*dt;const lateral=p.vx*fz-p.vz*fx,grip=1-Math.exp(-(p.stun>0?1.3:7)*dt);p.vx-=lateral*fz*grip;p.vz+=lateral*fx*grip;if(p.stun<=0)p.angle+=turn*dt*1.7*T.MathUtils.clamp(forward/18,-1.2,1.2);if(keys[' ']){p.vx*=Math.exp(-7*dt);p.vz*=Math.exp(-7*dt)}const vel=Math.hypot(p.vx,p.vz);if(vel>32){p.vx*=32/vel;p.vz*=32/vel}}
 else if(v.route.length&&p.stun<=0){let target=v.route[v.waypoint];if(Math.hypot(target.x-p.x,target.z-p.z)<5){v.waypoint=(v.waypoint+1)%v.route.length;target=v.route[v.waypoint]}const desired=Math.atan2(target.x-p.x,target.z-p.z),diff=Math.atan2(Math.sin(desired-p.angle),Math.cos(desired-p.angle));p.angle+=T.MathUtils.clamp(diff,-1.6*dt,1.6*dt);const blockedAhead=vehicles.some(o=>o!==v&&Math.hypot(o.physics.x-p.x,o.physics.z-p.z)<9&&(o.physics.x-p.x)*fx+(o.physics.z-p.z)*fz>1);const cruise=blockedAhead?0:v.cruise*(Math.abs(diff)> .6?.45:1),rate=1-Math.exp(-1.8*dt);p.vx+=(Math.sin(p.angle)*cruise-p.vx)*rate;p.vz+=(Math.cos(p.angle)*cruise-p.vz)*rate}else if(v===controlled&&!driving){p.vx*=Math.exp(-2*dt);p.vz*=Math.exp(-2*dt)}integrate(p,dt,blocked)}
 for(let pass=0;pass<2;pass++)for(let i=0;i<vehicles.length;i++)for(let j=i+1;j<vehicles.length;j++){const a=vehicles[i].physics,b=vehicles[j].physics;const hit=collide(a,b);if(hit>3&&(i===0||j===0))impactEffect((a.x+b.x)/2,(a.z+b.z)/2,hit)}
 for(const p of people){stepPerson(p.state,dt,blocked,!driving&&hp>0?{x:player.position.x,z:player.position.z}:undefined);for(const v of vehicles){const oldX=p.state.x,oldZ=p.state.z;const power=vehiclePerson(v.physics,p.state);if(power>0)damagePerson(p.state,Math.round(power*3),v===controlled&&driving);if(blocked(p.state.x,p.state.z,.5)){p.state.x=oldX;p.state.z=oldZ;p.state.vx*=.1;p.state.vz*=.1}if(power>1&&v===controlled&&driving){shake=Math.min(.35,power*.015);notice=power>=6?'보행자가 충격으로 넘어졌습니다':'보행자가 충격에 밀려났습니다';noticeTime=1.2}}const target={x:player.position.x,z:player.position.z,available:!driving&&hp>0};let clearLine=true;for(let k=1;k<5;k++){if(blocked(p.state.x+(target.x-p.state.x)*k/5,p.state.z+(target.z-p.state.z)*k/5,.2))clearLine=false}const damage=combatStep(p.state,dt,target,clearLine);if(damage&&hurtTimer<=0){hp=Math.max(0,hp-damage);hurtTimer=.55;shake=.2;notice='공격받았습니다! 체력 -'+damage;noticeTime=1;if(hp===0){speed=0;clear();player.rotation.x=1.4}}p.arm.rotation.x=p.state.swing>0?-Math.sin((.3-p.state.swing)/.3*Math.PI)*1.8:0;
 p.mesh.position.set(p.state.x,Math.sin(p.state.lean)*.3,p.state.z);p.mesh.rotation.set(p.state.lean,p.state.heading,0)}
 for(const v of vehicles){v.mesh.position.set(v.physics.x,0,v.physics.z);v.mesh.rotation.y=v.physics.angle}if(driving){yaw=controlled.physics.angle;speed=Math.hypot(controlled.physics.vx,controlled.physics.vz)}}
function onKey(e:KeyboardEvent){const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys[k]=e.type==='keydown';if(e.type==='keydown'&&!e.repeat){if(k==='e')interact();if(k==='f')attack();if(k==='escape'){paused=!paused;clear()}if(k==='r')reset()}}const down=(e:PointerEvent)=>{if(paused||(e.pointerType!=='touch'&&e.button!==2))return;e.preventDefault();drag=true;px=e.clientX;renderer.domElement.setPointerCapture(e.pointerId)},move=(e:PointerEvent)=>{if(drag){if(e.pointerType!=='touch'&&(e.buttons&2)===0){drag=false;return}orbit-=(e.clientX-px)*.007;px=e.clientX}},up=()=>{drag=false},contextMenu=(e:MouseEvent)=>{e.preventDefault()};window.addEventListener('keydown',onKey);window.addEventListener('keyup',onKey);window.addEventListener('blur',clear);renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',up);renderer.domElement.addEventListener('lostpointercapture',up);renderer.domElement.addEventListener('contextmenu',contextMenu);const resize=()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix()};window.addEventListener('resize',resize);resize();camera.position.set(13,11,26);
function animate(now:number){frame=requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.045);last=now;if(!paused&&hp>0){hurtTimer=Math.max(0,hurtTimer-dt);elapsed+=dt;const f=Number(keys.w||keys.arrowup||false)-Number(keys.s||keys.arrowdown||false),turn=Number(keys.a||keys.arrowleft||false)-Number(keys.d||keys.arrowright||false);accumulator+=dt;while(accumulator>=1/120){physicsStep(1/120,f,turn);accumulator-=1/120}if(!driving){const a=yaw+orbit;const dx=-Math.sin(a)*f-Math.cos(a)*turn,dz=-Math.cos(a)*f+Math.sin(a)*turn,len=Math.hypot(dx,dz),v=keys.shift?9:5;if(len){const nx=player.position.x+dx/len*v*dt,nz=player.position.z+dz/len*v*dt;if(!blocked(nx,player.position.z,.5))player.position.x=nx;if(!blocked(player.position.x,nz,.5))player.position.z=nz;player.rotation.y=Math.atan2(dx,dz);legs[0].rotation.x=Math.sin(elapsed*12)*.6;legs[1].rotation.x=-legs[0].rotation.x}else legs.forEach(l=>l.rotation.x=0);speed=len?v:0}attackTime=Math.max(0,attackTime-dt);attackCooldown=Math.max(0,attackCooldown-dt);noticeTime=Math.max(0,noticeTime-dt);const punch=attackTime>0?Math.sin((1-attackTime/.28)*Math.PI):0;fist.rotation.x=-punch*1.6;fist.position.z=punch*.65;fist.position.y=1.2+punch*.2;sparkLife=Math.max(0,sparkLife-dt);sparks.forEach((s,i)=>{s.visible=sparkLife>0;const t=.35-sparkLife,angle=i/12*Math.PI*2;s.position.set(sparkOrigin.x+Math.cos(angle)*t*8,sparkOrigin.y+t*3-t*t*12,sparkOrigin.z+Math.sin(angle)*t*8)});const pos=driving?ride.position:player.position;if(mission<3&&pos.distanceTo(targets[mission])<4.7)mission++;const target=targets[Math.min(mission,2)];ring.visible=beam.visible=mission<3;ring.position.copy(target).y=.2;beam.position.copy(target).y=8;ring.scale.setScalar(1+Math.sin(elapsed*3)*.06);const a=(driving?yaw+Math.PI:yaw)+orbit,dist=driving?16:13;camera.position.lerp(new T.Vector3(pos.x+Math.sin(a)*dist,driving?10:11,pos.z+Math.cos(a)*dist),1-Math.exp(-dt*5));shake*=Math.exp(-7*dt);camera.position.x+=Math.sin(elapsed*91)*shake;camera.position.y+=Math.cos(elapsed*78)*shake;camera.lookAt(pos.x,1.8,pos.z)}
if(now-lastHud>100){lastHud=now;const pos=driving?ride.position:player.position;report({hp,hurt:hurtTimer>0,speed:Math.round(Math.abs(speed)*3.6),driving,mission,distance:mission<3?Math.round(pos.distanceTo(targets[mission])):0,paused,hint:noticeTime>0?notice:mission===3?'배달 완료 · 자유롭게 성수동을 탐험하세요':driving?'E 내려서 탐험하기 · SPACE 브레이크':pos.distanceTo(ride.position)<6?'E 키를 눌러 차량에 탑승하세요':'WASD 이동 · F 공격 · 노란 빛을 따라가세요',error:''});const c=document.getElementById('minimap') as HTMLCanvasElement|null,ctx=c?.getContext('2d');if(ctx){ctx.fillStyle='#293c3e';ctx.fillRect(0,0,220,220);const cv=(v:number)=>110+v*.88;ctx.fillStyle='#67716a';solids.forEach(b=>ctx.fillRect(cv(b.x-b.w/2),cv(b.z-b.d/2),b.w*.88,b.d*.88));ctx.strokeStyle='#a3aaa0';ctx.lineWidth=2;for(const a of [-70,0,70]){ctx.beginPath();ctx.moveTo(cv(a),0);ctx.lineTo(cv(a),220);ctx.stroke()}for(const a of [-65,0,65]){ctx.beginPath();ctx.moveTo(0,cv(a));ctx.lineTo(220,cv(a));ctx.stroke()}if(mission<3){ctx.fillStyle='#eaff79';ctx.beginPath();ctx.arc(cv(targets[mission].x),cv(targets[mission].z),5,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#aac7d3';vehicles.slice(1).forEach(v=>ctx.fillRect(cv(v.physics.x)-2,cv(v.physics.z)-2,4,4));ctx.fillStyle='#ed905d';ctx.fillRect(cv(ride.position.x)-3,cv(ride.position.z)-3,6,6);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(cv(pos.x),cv(pos.z),4,0,Math.PI*2);ctx.fill()}}people.forEach(p=>{p.bar.position.set(p.state.x,p.state.hp>0?2.7:.8,p.state.z);p.bar.quaternion.copy(camera.quaternion);p.fill.scale.x=p.state.hp/100;p.fill.position.x=-(1-p.state.hp/100)*.95;(p.fill.material as T.MeshBasicMaterial).color.set(p.state.aggro>0?'#ef795c':p.state.hp<35?'#e8b64b':'#86df88')});renderer.render(scene,camera)}frame=requestAnimationFrame(animate);
return{attack,key:(k,v)=>{keys[k]=v},interact,reset,pause:()=>{paused=!paused;clear()},dispose:()=>{cancelAnimationFrame(frame);window.removeEventListener('keydown',onKey);window.removeEventListener('keyup',onKey);window.removeEventListener('blur',clear);window.removeEventListener('resize',resize);renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointermove',move);renderer.domElement.removeEventListener('pointerup',up);renderer.domElement.removeEventListener('pointercancel',up);renderer.domElement.removeEventListener('lostpointercapture',up);renderer.domElement.removeEventListener('contextmenu',contextMenu);scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>{if(m.map)m.map.dispose();m.dispose()})}});renderer.dispose();renderer.domElement.remove()}}}
