// Menu names and images: McDonald's Korea. Prices below are game economy values.
export const MCD_MENU = {
  bigmac: {
    name: '빅맥 세트',
    price: 7500,
    sell: 3000,
    hp: 30,
    energy: 0,
    food: 1,
    description: '쇠고기 패티 두 장 · 후렌치 후라이 · 콜라',
    image: '/mcd/bigmac.png',
    source: 'https://www.mcdonalds.co.kr/kor/menu/detail/178/3/21',
  },
  shanghai: {
    name: '맥스파이시 상하이 버거 세트',
    price: 7500,
    sell: 3000,
    hp: 30,
    energy: 0,
    food: 1,
    description: '매콤한 닭가슴살 패티 · 감자와 콜라',
    image: '/mcd/shanghai.png',
    source: 'https://www.mcdonalds.co.kr/kor/menu/detail/603/4/21',
  },
  burger1955: {
    name: '1955 버거 세트',
    price: 9000,
    sell: 3600,
    hp: 40,
    energy: 0,
    food: 1,
    description: '쇠고기 패티와 구운 양파 · 감자와 콜라',
    image: '/mcd/1955.png',
    source: 'https://www.mcdonalds.co.kr/kor/menu/detail/2/3/1',
  },
  fries: {
    name: '후렌치 후라이 Small',
    price: 2200,
    sell: 800,
    hp: 12,
    energy: 0,
    food: 1,
    description: '바삭한 감자 사이드',
    image: '/mcd/fries.png',
    source: 'https://www.mcdonalds.co.kr/kor/menu/detail/88/6/8',
  },
  nuggets: {
    name: '맥너겟 4조각',
    price: 2800,
    sell: 1000,
    hp: 16,
    energy: 0,
    food: 1,
    description: '한입 크기로 즐기는 치킨 네 조각',
    image: '/mcd/nuggets.png',
    source: 'https://www.mcdonalds.co.kr/kor/menu/detail/284/6/8',
  },
  mccoffee: {
    name: '아이스 아메리카노 Large',
    price: 3000,
    sell: 1200,
    hp: 10,
    energy: 1,
    food: 0,
    description: '차갑게 즐기는 갓 추출한 커피',
    image: '/mcd/coffee.png',
    source: 'https://www.mcdonalds.co.kr/kor/menu/detail/731/6/9',
  },
} as const;
export type McdItem = keyof typeof MCD_MENU;
